server:
  port: 8080

spring:
  application:
    name: BookMall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmall?serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    servlet:
      load-on-startup: 1
springdoc:
  packages-to-scan: com.bookmall.Controller




# 自定义属性
jwt:
  secret-key: aDIwdTA0eHUwNGFuMjZoZTYyMzHlm77kuabllYbln47pobnnm67lr4bpkqU=
  expire: 3600000



